# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='pyppl_runners',
    version='0.0.5',
    description='More strict check of job success for PyPPL',
    python_requires='==3.*,>=3.6.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={
        "pyppl_runner": [
            "pyppl_runner_dry = pyppl_runners:DRY_RUNNER",
            "pyppl_runner_sge = pyppl_runners:SGE_RUNNER",
            "pyppl_runner_slurm = pyppl_runners:SLURM_RUNNER",
            "pyppl_runner_ssh = pyppl_runners:SSH_RUNNER"
        ]
    },
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['cmdy', 'diot', 'psutil==5.*', 'pyppl'],
    extras_require={"dev": ["pytest", "pytest-cov"]},
)
